const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const [width,height] of [[390,844],[844,390],[1280,800]]){
const p=await b.newPage({viewport:{width,height}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));
const code=fs.readFileSync('js/game.js','utf8').replace('  /* ---- 启动 ---- */',`window.__exp={checkpoint:function(n){wave=n;openUpgrade();},player:function(){return player;},diff:currentDiff,stats:function(){return runStats;},clearBoss:function(){enemies=[];spawnSeq=[];boss=null;bossKilled=true;},finish:gameOver};\n  /* ---- 启动 ---- */`);
await p.route('**/js/game.js',r=>r.fulfill({body:code,contentType:'text/javascript'}));await p.goto(pathToFileURL(path.resolve('index.html')).href);
const launch=await p.locator('#btn-launch').boundingBox();assert(launch.y+launch.height<=height,`Launch outside viewport ${width}`);
await p.locator('#panel-start .audio-settings summary').click();await p.locator('#panel-start [data-volume="music"]').fill('25');await p.locator('#panel-start [data-volume="sfx"]').fill('70');assert.deepEqual(await p.evaluate(()=>DFJ.Audio.volumes()),{music:.25,sfx:.7});await p.reload();assert.deepEqual(await p.evaluate(()=>DFJ.Audio.volumes()),{music:.25,sfx:.7});
await p.locator('[data-mode="roguelike"]').click();await p.locator('#btn-launch').click();await p.evaluate(()=>__exp.checkpoint(3));await p.locator('#upgrade-cards button').first().click();assert.equal(await p.locator('#choice-title').innerText(),'武器进化');await p.locator('[data-choice="pierce"]').click();assert.equal(await p.locator('#choice-title').innerText(),'选择下一段路线');await p.locator('[data-choice="elite"]').click();assert.equal(await p.evaluate(()=>__DFJ_PROBE.state().wave),4);assert.equal(await p.evaluate(()=>__exp.player().evolution),'pierce');assert.equal(await p.evaluate(()=>__exp.diff().hpMul/DFJ.Logic.difficulty(4,'normal').hpMul),1.25);
await p.evaluate(()=>__exp.checkpoint(6));assert((await p.locator('#choice-subtitle').innerText()).includes('2'));await p.locator('#upgrade-cards button').first().click();assert((await p.locator('#choice-subtitle').innerText()).includes('1'));await p.locator('#upgrade-cards button').first().click();assert.equal(await p.locator('#choice-title').innerText(),'选择下一段路线');await p.locator('[data-choice="repair"]').click();assert.equal(await p.evaluate(()=>__exp.diff().hpMul/DFJ.Logic.difficulty(7,'normal').hpMul),1);
for(const checkpoint of [9,12,15,18]){await p.evaluate(n=>__exp.checkpoint(n),checkpoint);let picks=0;while((await p.locator('#choice-title').innerText())==='选择强化'){await p.locator('#upgrade-cards button').first().click();picks++;}assert.equal(picks,checkpoint===12||checkpoint===15?2:1,'Elite extra upgrades stop after the third completion');await p.locator('[data-choice="'+(checkpoint===18?'repair':'elite')+'"]').click();}
await p.evaluate(()=>__exp.finish());assert((await p.locator('#run-over').innerText()).includes('贯穿脉冲'));await p.locator('#btn-menu-over').click();await p.locator('[data-mode="bossrush"]').click();await p.locator('#btn-launch').click();for(let i=1;i<=5;i++){await p.evaluate(()=>__exp.clearBoss());await p.waitForTimeout(80);if(i<5){assert.equal(await p.locator('#choice-title').innerText(),'战间整备');await p.locator('[data-choice="damage"]').click();}}assert.equal(await p.evaluate(()=>__DFJ_PROBE.state().STATE),'victory');
await p.locator('#btn-menu-victory').click();await p.locator('[data-mode="challenge"]').click();await p.locator('#btn-launch').click();assert.equal(await p.evaluate(()=>__exp.player().weapon),2);assert.equal(await p.evaluate(()=>__exp.player().evolution||null),null);await p.evaluate(()=>{__exp.stats().seconds=180;});await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>__DFJ_PROBE.state().STATE),'victory');await p.locator('#btn-menu-victory').click();
assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);await p.screenshot({path:'test/artifacts/expedition-'+width+'.png'});await p.close();console.log('PASS expedition, 5 bosses, timed victory, volumes and layout '+width);
}}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
